# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ijin-yeong/Desktop/project_list_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import wx
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
import sys, os

from pathlib import Path

class Ui_Form(QtWidgets.QWidget):

    sc_width = 1920
    sc_height = 1080
    root_path = Path(os.path.abspath('')).parent

    app_font = QFont('Arial',24)

    def __init__(self):
        super().__init__()
        self.setupUi()

    def paintEvent(self, a0: QPaintEvent):
        painter = QtGui.QPainter(self)
        painter.drawRect(self.rect())


        pix = QtGui.QPixmap()  # Change to the relative path of your own image
        img_path = str(Ui_Form.root_path) + '/imgs/ui/background-img.png'
        pix.load(img_path)



        painter.drawPixmap(self.rect(), pix)


    def setupUi(self):

        self.setWindowTitle('Project List')
        self.resize(800,600)

        self.title_label = QtWidgets.QLabel()
        self.title_label.setText('Project List')
        self.title_label.setAlignment(QtCore.Qt.AlignHCenter)
        self.title_label.setFont(Ui_Form.app_font)

        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.setLayout(self.vertical_layout)
        self.vertical_layout.addWidget(self.title_label)





if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)

    form = Ui_Form()
    form.paintEngine()

    form.show()

    sys.exit(app.exec_())
