# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ijin-yeong/Desktop/project_list_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
class Ui_Form(QtWidgets.QWidget):
    def addListItem(self, text):
        item = QtWidgets.QListWidgetItem(text)
        self.m_list.addItem(item)
        widget = QtWidgets.QWidget(self.m_list)
        button = QtWidgets.QToolButton(widget)
        button.setText(text)
        button.setMaximumHeight(50)

        font = QtGui.QFont()
        font.setPointSize(24)
        button.setFont(font)

        layout = QtWidgets.QHBoxLayout(widget)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addStretch()
        layout.addWidget(button)
        self.m_list.setItemWidget(item, widget)
        button.clicked.connect(
            lambda: self.handleButtonClicked(item))

    def handleButtonClicked(self, item):
        print(item.text())

    def setupUi(self, Form):

        self.entries = ['영화리뷰 감성 분류기','얼굴 인식(Sample)','얼굴인식 (Easyjin version)','추가 예정','추가 예정','추가 예정','추가 예정','추가 예정','추가 예정','추가 예정']

        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 581, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.m_list = QtWidgets.QListWidget(self.gridLayoutWidget)

        #listview item entry add
        self.addListItem('test1')
        self.addListItem('test2')


        self.gridLayout.addWidget(self.m_list, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ProJect List"))

    def paintEvent(self, a0: QPaintEvent):
        painter = QtGui.QPainter(self)
        painter.drawRect(self.rect())
        pix = QtGui.QPixmap("./imgs/ui/background-img.png")  # Change to the relative path of your own image
        painter.drawPixmap(self.rect(), pix)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)


    Form.show()
    sys.exit(app.exec_())
